Setup github auth
- Currently github auth is still disabled, since we kept experiencing a redirect_uri error

> AuthorizationError: The redirect_uri MUST match the registered callback URL for this application.